deploy-server:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}
  runs-on: [self-hosted, deploy, linux]

  steps:
    - uses: actions/checkout@v4
    - name: Copie du site
      run: |
        sudo cp index.html /var/www/html/index.html
        sudo systemctl reload nginx
